[package]
name = "ephemeris"
version = "0.1.0"
authors = ["Roman A. Voronkin <roman.voronkin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ephemeris"

[dependencies]
approx = "0.3.2"
lazy_static = "1.4.0"
num-traits = "0.2.14"
